### ISSUE TITLE
Breadcrumbs links are broken

### ISSUE THREAD

**Issue by marco-lavagnino** [inueni/django-subadmin#15]
In the last release (3.2.2), the template on the breadcrumbs was changed to check for the attribute `has_view_permission` ([link](https://github.com/inueni/django-subadmin/blob/01f4556e7965411db5df526a74c377df44b376f4/subadmin/templates/subadmin/breadcrumbs.html#L6)).

However, [the template tag still populates the attribute `has_change_permission`](https://github.com/inueni/django-subadmin/blob/01f4556e7965411db5df526a74c377df44b376f4/subadmin/templatetags/subadmin_tags.py#L31).

As a result, breadcrumbs are rendered without links:
<img width="461" alt="image" src="https://github.com/inueni/django-subadmin/assets/8427482/56a41f16-f2b2-4c46-8ee4-8add7762e751">

A quickfix for users is to downgrade the package to version `3.2.1`.

**Comment by sect2k** [comment]
Thanks for catching this. I had and off feeling about the last PR, but it was just before vacation and I wanted to get it out the door, before I left. New release is being published as I type.
