### ISSUE TITLE
Thread safety for Django < 1.11

### ISSUE THREAD

**Issue by vstoykov** [inueni/django-subadmin#2]
I read about your workaround and thing that this can cause problems in multithreaded deployments and there can be a race condition.

The real possibility probably is very small but still it's there. I'm wondering if it will better to add some kind of lock to guard against these race conditions.

**Comment by sect2k** [comment]
@vstoykov while I don't believe that there can be any negative side efects from current workaround, thread safety considered, you proposal got me thinking of alternative solutions and I think I found the least complicated one. I'll do some testing tomorrow and if all goes well I'll release a new version.

**Comment by sect2k** [comment]
@vstoykov this is fixed in 1.9.1 release. Instead of opting for some locking scheme, I decided to backport `get_form` from Django 1.11. It's not the most elegant solution, since it duplicates code, but it's in my opinon, the cleanest. Backported code is only run on on Django < 1.11.
